name: mateo_mobile
description: The Flutter implementation of Mateo Mobile.
version: 0.0.1
publish_to: none
resolution: workspace

platforms:
  android:
  ios:

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  diacritic: ^0.1.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  oh_my_flutter: ^0.25.0
  slang: ^4.19.2

dev_dependencies:
  alchemist: ^0.14.0
  build_runner: ^2.15.0
  dotdart: ^0.10.2
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.19.0

dotdart:
  output: lib/src/gen/
  svg:
    - assets/icons/
    - assets/flags/
  lottie:
    - assets/animated_icons/

flutter:
  assets:
    - assets/flags/
    - assets/icons/
    - assets/animated_icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_variable.ttf
        - asset: assets/fonts/inter_italic.ttf
          style: italic
