part of 'mateo_color_scheme.dart';

class _LightMateoColorScheme extends MateoColorScheme {
  _LightMateoColorScheme({
    required MateoPalette palette,
    required Color onPrimary,
  }) : super(
         background: Colors.white,
         colors: MateoColorsColorScheme(
           neutral: MateoColorVariantColorScheme(
             solid: palette.neutral[12],
             onSolid: Colors.white,
           ),
         ),
         text: MateoTextColorScheme(
           primary: palette.neutral[12],
           secondary: palette.neutral[10],
           tertiary: palette.neutral[9],
           disabled: palette.neutral[9],
           inverse: Colors.white,
           profit: palette.green[10],
         ),
         selectionHighlight: palette.primary[9].withValues(alpha: 0.30),
         buttons: MateoButtonsColorScheme(
           primary: MateoButtonColorScheme(
             background: palette.primary[9],
             backgroundPressed: palette.primary[9],
             backgroundDisabled: palette.neutral[4],
             foreground: onPrimary,
             foregroundDisabled: palette.neutral[9],
           ),
           secondary: MateoButtonColorScheme(
             background: palette.primary[2],
             backgroundPressed: palette.primary[2],
             backgroundDisabled: palette.neutral[4],
             foreground: palette.primary[9],
             foregroundDisabled: palette.neutral[9],
           ),
           tertiary: MateoButtonColorScheme(
             background: palette.neutral[12],
             backgroundPressed: palette.neutral[12],
             backgroundDisabled: palette.neutral[4],
             foreground: Colors.white,
             foregroundDisabled: palette.neutral[9],
           ),
           text: MateoButtonColorScheme(
             background: Colors.transparent,
             backgroundPressed: Colors.transparent,
             backgroundDisabled: Colors.transparent,
             foreground: palette.neutral[12],
             foregroundDisabled: palette.neutral[9],
           ),
           danger: MateoButtonColorScheme(
             background: palette.red[10],
             backgroundPressed: palette.red[10],
             backgroundDisabled: palette.neutral[4],
             foreground: Colors.white,
             foregroundDisabled: palette.neutral[9],
           ),
           success: MateoButtonColorScheme(
             background: palette.green[9],
             backgroundPressed: palette.green[9],
             backgroundDisabled: palette.neutral[4],
             foreground: palette.green[12],
             foregroundDisabled: palette.neutral[9],
           ),
           searchBar: MateoSearchBarButtonColorScheme(
             background: Colors.white,
             backgroundPressed: Colors.white,
             foreground: palette.neutral[12],
             border: Colors.white,
             shadow: const Color(0x1A000000),
           ),
           floating: MateoFloatingButtonColorScheme(
             background: Colors.white,
             backgroundPressed: Colors.white,
             backgroundDisabled: palette.neutral[4],
             foreground: palette.neutral[12],
             foregroundDisabled: palette.neutral[9],
             border: Colors.white,
             shadow: const Color(0x1A000000),
           ),
           whatsapp: MateoBrandedButtonColorScheme(
             primary: MateoButtonColorScheme(
               background: palette.whatsapp[9],
               backgroundPressed: palette.whatsapp[9],
               backgroundDisabled: palette.neutral[4],
               foreground: palette.whatsapp[12],
               foregroundDisabled: palette.neutral[9],
             ),
             secondary: MateoButtonColorScheme(
               background: palette.whatsapp[3],
               backgroundPressed: palette.whatsapp[3],
               backgroundDisabled: palette.neutral[4],
               foreground: palette.whatsapp[11],
               foregroundDisabled: palette.neutral[9],
             ),
             tertiary: MateoButtonColorScheme(
               background: palette.whatsapp[12],
               backgroundPressed: palette.whatsapp[12],
               backgroundDisabled: palette.neutral[4],
               foreground: palette.whatsapp[9],
               foregroundDisabled: palette.neutral[9],
             ),
           ),
         ),
         overlay: const MateoOverlayColorScheme(scrim: Color(0x66000000)),
         bottomSheet: MateoBottomSheetColorScheme(
           background: Colors.white,
           handle: palette.neutral[6],
         ),
         toast: MateoToastColorScheme(
           success: MateoToastVariantColorScheme(
             background: palette.green[12],
             foreground: Colors.white,
             icon: palette.green[9],
           ),
           error: MateoToastVariantColorScheme(
             background: palette.red[12],
             foreground: Colors.white,
             icon: palette.red[9],
           ),
           warning: MateoToastVariantColorScheme(
             background: palette.amber[12],
             foreground: Colors.white,
             icon: palette.amber[9],
           ),
           info: MateoToastVariantColorScheme(
             background: palette.blue[12],
             foreground: Colors.white,
             icon: palette.blue[9],
           ),
           neutral: MateoToastVariantColorScheme(
             background: palette.neutral[12],
             foreground: Colors.white,
             icon: palette.neutral[8],
           ),
         ),
         scrollbar: MateoScrollbarColorScheme(
           thumb: palette.neutral[7],
           track: Colors.transparent,
         ),
         skeleton: MateoSkeletonColorScheme(
           bone: palette.neutral[3],
           shimmerGlow: palette.neutral[1],
           skeletonText: palette.neutral[8],
           skeletonTextGlow: palette.neutral[4],
         ),
         inverse: MateoInverseColorScheme(
           background: palette.neutral[12],
           onBackground: Colors.white,
           primary: palette.primary[3],
         ),
         controls: MateoControlsColorScheme(
           track: palette.neutral[6],
           trackFilled: palette.primary[9],
           indicator: palette.primary[9],
           indicatorForeground: onPrimary,
           caret: palette.primary[9],
         ),
         map: MateoMapColorScheme(
           background: palette.neutral[2],
           landcover: palette.green[5],
           landuse: palette.neutral[2],
           landuseBusiness: palette.neutral[2],
           landuseRecreation: palette.green[5],
           park: palette.green[5],
           water: palette.cyan[5],
           waterway: palette.cyan[5],
           building: palette.neutral[4],
           buildingOutline: palette.neutral[6],
           boundary: palette.neutral[7],
           tunnel: palette.neutral[6],
           road: Colors.white,
           labelHalo: Colors.white,
           administrativeLabel: palette.neutral[9],
           cityLabel: palette.neutral[11],
           townLabel: palette.neutral[8],
           neighborhoodLabel: palette.neutral[10],
           roadMajorLabel: palette.neutral[9],
           roadLocalLabel: palette.neutral[8],
           pointOfInterestLabel: palette.neutral[8],
           locationRadius: palette.teal[9].withValues(alpha: 0.15),
         ),
       );
}
