name: Repository configuration

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - .github/**
      - .release-please-manifest.json
      - RELEASES.md
      - release-please-config.json

permissions:
  contents: read

jobs:
  validate:
    name: Validate repository configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Validate repository configuration
        run: ruby .github/scripts/validate_repository_config.rb
